### ISSUE TITLE
error while getting serviceaccount for crossplane

### ISSUE THREAD

**Issue by roynilanjan** [salaboy/from-monolith-to-k8s#49]
Hi,
I am following this tutorial - https://github.com/salaboy/from-monolith-to-k8s/blob/main/platform/crossplane-dapr/pre-requisites.md 
In the step - Getting providers credentials:

SA=$(kubectl -n crossplane-system get sa -o name | grep provider-kubernetes | sed -e 's|serviceaccount\/|crossplane-system:|g')
kubectl create clusterrolebinding provider-kubernetes-admin-binding --clusterrole cluster-admin --serviceaccount="${SA}"
I am getting the following error :
error: serviceaccount must be <namespace>:<name> 

However when I run this :
kubectl -n crossplane-system get sa -o name :
I get the following output :
serviceaccount/default
serviceaccount/crossplane
serviceaccount/rbac-manager
I am running it on k3s and all the pods in crossplane-system are running.
Can you share some help ?

Thanks

**Comment by mickdelaney** [comment]
@roynilanjan did u figure it out ? 
i'm having the same problem.

**Comment by mickdelaney** [comment]
ok, the issue was when installing the current crossplane-contrib provider helm you should use yml like this.


```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: "crossplanecontrib/provider-helm:master"
```

then you can follow the steps as normal.
